version: "2"

services:
  mysql:
    image: hypriot/rpi-mysql
    container_name: mysql-main
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    networks:
      - proxy-network 

# Support pour reverse proxy - Common network interface for all containers
networks:
  proxy-network:
    external:
      name: proxy-network

