version: "2"

services:
  mysql:
    image: hypriot/rpi-mysql
    container_name: mysql-main
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_runtime:/var/lib/mysql
    networks:
      - proxy-network
    labels:
      - "traefik.enable=false"

# Support for reverse proxy - Common network interface for all containers
networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  mysql_runtime:
    external: true
